import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // auto-generated by flutterfire
import 'screens/slec_home_screen.dart';
import 'screens/student_portal/student_portal_screen.dart';
import 'package:cloud_firestore/cloud_firestore.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();


  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );


  runApp(const MyApp());    
}


class MyApp extends StatelessWidget {
  const MyApp({super.key});


  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'SLEC Campus Connect',
      theme: ThemeData(
        brightness: Brightness.light,
        primaryColor: Colors.deepPurple,
        scaffoldBackgroundColor: Colors.white,
        cardColor: Colors.white,
        dialogBackgroundColor: Colors.white,
        canvasColor: Colors.white,
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          foregroundColor: Colors.black,
          elevation: 0,
        ),
        bottomNavigationBarTheme: const BottomNavigationBarThemeData(
          backgroundColor: Colors.white,
          selectedItemColor: Colors.deepPurple,
          unselectedItemColor: Colors.grey,
          showUnselectedLabels: true,
        ),
        textTheme: GoogleFonts.interTextTheme(),
        colorScheme: ColorScheme.fromSwatch(
          primarySwatch: Colors.deepPurple,
          backgroundColor: Colors.white,
          brightness: Brightness.light,
        ).copyWith(surface: Colors.white),
      ),
      home: const SlecHomeScreen(),


      routes: {
        '/portal': (context) => const StudentPortalScreen(),
      },
    );
  }
}
class FirestoreTestScreen extends StatelessWidget {
  const FirestoreTestScreen({super.key});


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Firestore Realtime Test')),
      body: StreamBuilder<QuerySnapshot>(
        stream: FirebaseFirestore.instance
            .collection('students')
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return const Center(child: CircularProgressIndicator());
          }


          final docs = snapshot.data!.docs;
          print('Docs count: ${docs.length}');




          if (docs.isEmpty) {
            return const Center(child: Text('No students found'));
          }


          return ListView(
            children: docs.map((doc) {
              return ListTile(
                title: Text(doc.data().toString().contains('name') ? doc['name'] : 'No name'),
subtitle: Text(doc.data().toString().contains('email') ? doc['email'] : ''),

              );
            }).toList(),
          );
        },
      ),
    );
  }
}





